[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
solc = "0.8.20"
evm_version = "cancun"
remappings = [
    "@layerzerolabs/lz-evm-oapp-v2=lib/LayerZero-v2/oapp",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/protocol/"
]


[etherscan]
polygon-mumbai = { key = "${POLYGON_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
ethereum-goerli = { key = "${ETHERSCAN_API_KEY}", url = "https://goerli.etherscan.io/api" }
ethereum-sepolia = {key="${ETHERSCAN_API_KEY}",url="https://api-sepolia.etherscan.io/api"}
optimism-mainnet = {key="${OPTIMISM_API_KEY}",url="https://api-optimistic.etherscan.io/api"}
moonbase = {key="${MOONBEAM_API_KEY}",url="https://api-moonbase.moonscan.io/api"}
moonbeam = {key="${MOONBEAM_API_KEY}",url="https://api-moonbeam.moonscan.io/api"}

[rpc_endpoints]
mainnet = "${ALCHEMY_MAINNET_URL}"
goerli = "${ALCHEMY_GOERLI_URL}"
polygon = "${GOERLI_POLYGON_URL}"
mumbai = "${ALCHEMY_MUMBAI_URL}"
sepolia = "${ALCHEMY_SEPOLIA_URL}"
optimism = "${ALCHEMY_OPTIMISM_URL}"
moonbase = "https://rpc.api.moonbase.moonbeam.network"
moonbeam = "https://rpc.api.moonbeam.network"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config